language: python
cache: pip
matrix:
  include:
    - python: 2.6
      env:
        - pylinter=old
        - nodoc=true
    - python: 2.7
      env: nodoc=true
    - dist: trusty
      sudo: required
      python: 2.7
install:
  - if [ "$pylinter" = "old" ];
        then pip install "astroid<1.3" "pylint<1.4" "testfixtures<6";
        else pip install pylint;
    fi
  - python setup.py install
script:
  - opsspace-test
  - if [ "$pylinter" = "old" ];
        then pylint --rcfile <(sed 's/load-plugins=/#/g' test/pylint.cfg) cmstoolbox;
        else pylint --rcfile test/pylint.cfg cmstoolbox;
    fi
