language: python
cache: pip
matrix:
  include:
    - python: 2.6
      env: PYLINTER=old
    - python: 2.7
    - dist: trusty
      sudo: required
      python: 2.7
      env: CHECKDOC=true
install:
  - if [ "$PYLINTER" = "old" ]; then pip install "astroid<1.3" "pylint<1.4" "testfixtures<6"; fi
  - python setup.py install
script:
  - cd test
  - ./test_example.py
  - ./test_siteinfo.py
  - ./test_sitereadiness.py
  - ./test_unmerged_cleaner.py
