language: python
cache: pip
dist: trusty
matrix:
  include:
    - python: 2.7
    - dist: xenial
      python: 3.7
      env:
        - nodoc=true
install:
  - python setup.py install
script:
  - opsspace-test
