language: python
cache: pip
matrix:
  include:
    - python: 2.6
      env: PYLINTER=old
    - python: 2.7
    - dist: trusty
      sudo: required
      python: 2.7
install:
  - if [ "$PYLINTER" = "old" ]; then pip install pylint==1.3.1; fi
  - ./setup.py install --force
script: test/run_tests.sh CMSToolBox
